"""Explicit v2 assessment for the selector-drift workflow test scenario.

Expected facts are fixed by the synthetic scene, not generated by the policy
under test. There is no business observation, so business recovery is unknown.
"""

from backend.app.agent.schemas import DiagnosticAssessment


def selector_assessment(service_id: str, deployment_id: str) -> DiagnosticAssessment:
    return DiagnosticAssessment(
        schema_version="v2",
        problem_domain="deployment_configuration",
        symptoms=[{
            "summary": "Service selector differs from the registered deployment labels.",
            "evidence_ids": [service_id, deployment_id],
        }],
        root_cause_hypotheses=[{
            "summary": "Observed selector drift prevents routing to the registered workload.",
            "status": "supported",
            "evidence_ids": [service_id, deployment_id],
        }],
        missing_evidence=["Fresh registered business checks after remediation."],
        next_investigation=["Verify resource readiness and registered business checks after approval and repair."],
        resource_status="not_ready",
        business_status="unknown",
        unverified_scope=["Business availability, external ingress and sustained recovery."],
    )
